[libraries]
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
kotlin-logging = "io.github.oshai:kotlin-logging:4.0.0-beta-29"
slf4j-api = "org.slf4j:slf4j-api:2.0.7"
