[libraries]
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
kotlinx-coroutine-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.5"
slf4j-api = "org.slf4j:slf4j-api:2.0.7"
logback-classic = "ch.qos.logback:logback-classic:1.4.7"
slf4j-jdk14 = "org.slf4j:slf4j-jdk14:2.0.7"
checker-qual = "org.checkerframework:checker-qual:3.37.0"
