name: Build

on:
  push:
    branches:
      - 'master'
      - 'refactor'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: '.java-version'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-service-agree: "yes"

      - name: Build
        run: ./gradlew build

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports
          path: build/reports/

      - name: Native Test
        run: ./gradlew nativeTest

      - name: Print all files on failure
        if: failure()
        run: find

